# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBaseExample
   pod 'Firebase/Core'
   pod 'Firebase/Firestore'
   pod 'FirebaseFirestoreSwift'
   pod 'Firebase/Analytics'
   pod 'Firebase/RemoteConfig'
   pod 'Firebase/Database'
   pod 'FirebaseUI'

end
